"""Add chart_type

Revision ID: 893b37b0acaf
Revises: 
Create Date: 2025-05-14 14:21:13.295445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893b37b0acaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.drop_column('run_timestamp')

    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chart_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_column('chart_type')

    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_timestamp', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
