"""Add fill_color and border_color to Chart

Revision ID: a87056fc6ea0
Revises: 6c25e5082775
Create Date: 2025-05-15 14:15:17.415370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87056fc6ea0'
down_revision = '6c25e5082775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fill_color', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('border_color', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_column('border_color')
        batch_op.drop_column('fill_color')

    # ### end Alembic commands ###
